// LuxeNova — Full Product Catalog with Indian Rupee (₹) Pricing
// Categories: audio, electronics, fashion, footwear, home, men, women, kids, phones, accessories, watches, fragrance, jewellery, bags

const PRODUCTS = [

  // ══════════════════════════════════════════════════════════════
  //  AUDIO & SOUND
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-1",
    name: "AuraPro Wireless Noise Cancelling Headphones",
    category: "audio",
    categoryLabel: "Audio & Sound",
    price: 4999,
    originalPrice: 9999,
    discountPercent: 50,
    rating: 4.8,
    reviewsCount: 1420,
    badge: "Bestseller",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/aura_headphones.jpg",
    description: "Immerse yourself in pure studio sound with Active Noise Cancellation, 40-hour battery life, and ultra-soft memory foam ear cushions engineered for all-day comfort.",
    features: ["Hybrid Active Noise Cancellation (up to 35dB)", "40 Hours Playtime on single charge", "Fast charging: 10 mins = 4 hours playback", "Multipoint Bluetooth 5.3 connection", "Built-in quad microphones with AI voice clarity"]
  },
  {
    id: "prod-10",
    name: "TrueSound Bass Boost Wireless Earbuds",
    category: "audio",
    categoryLabel: "Audio & Sound",
    price: 1799,
    originalPrice: 3999,
    discountPercent: 55,
    rating: 4.6,
    reviewsCount: 3890,
    badge: "Mega Saver",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/truesound_earbuds.jpg",
    description: "13mm titanium composite drivers delivering deep resonant bass and crisp highs. Quad-mic Environmental Noise Cancellation ensures crystal-clear call quality anywhere.",
    features: ["13mm dynamic titanium audio drivers", "Up to 50 hours total playtime with pocket charging case", "40ms ultra-low latency Beast Gaming Mode", "IPX5 Sweat and splash resistance", "Smart touch controls for music, volume & voice assistant"]
  },
  {
    id: "audio-3",
    name: "SoundBar Pro 2.1 Bluetooth Speaker",
    category: "audio",
    categoryLabel: "Audio & Sound",
    price: 3499,
    originalPrice: 7999,
    discountPercent: 56,
    rating: 4.7,
    reviewsCount: 982,
    badge: "Deep Bass",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/speaker_bluetooth.jpg",
    description: "Powerful 2.1 channel soundbar with dedicated subwoofer for thunderous bass. RGB lighting, 360° surround sound and 20-hour battery life.",
    features: ["120W total output (80W + 40W subwoofer)", "Bluetooth 5.1, AUX & USB playback", "20-hour playtime on single charge", "RGB lighting with 7 color modes", "IPX5 water resistance for outdoor use"]
  },

  // ══════════════════════════════════════════════════════════════
  //  WATCHES & WEARABLES
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-2",
    name: "Titanium Pro AMOLED Smartwatch",
    category: "watches",
    categoryLabel: "Watches & Wearables",
    price: 3499,
    originalPrice: 6999,
    discountPercent: 50,
    rating: 4.7,
    reviewsCount: 890,
    badge: "Trending",
    badgeType: "badge-exclusive",
    inStock: true,
    image: "images/products/amoled_smartwatch.jpg",
    description: "1.43-inch Always-on AMOLED display encased in aircraft-grade zinc alloy. Features 110+ sports modes, Bluetooth calling, SpO2 monitor, and 7-day battery endurance.",
    features: ["1.43\" Ultra Retina AMOLED (466x466 px)", "Bluetooth calling with loud HD speaker & mic", "24/7 Heart rate, SpO2 & Sleep tracking", "IP68 Water & Dust Resistant", "Over 200+ customizable cloud watch faces"]
  },
  {
    id: "prod-9",
    name: "Classic Chronograph Stainless Steel Watch",
    category: "watches",
    categoryLabel: "Watches & Wearables",
    price: 4199,
    originalPrice: 8499,
    discountPercent: 51,
    rating: 4.8,
    reviewsCount: 512,
    badge: "Premium",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/classic_chronograph.jpg",
    description: "Timeless elegance with a sapphire crystal dial, luminous hands, Japanese quartz movement, and surgical grade 316L solid stainless steel link bracelet.",
    features: ["Scratch-resistant anti-reflective Sapphire Crystal glass", "Precision Japanese Miyota chronograph quartz movement", "50M / 5ATM Water Resistant", "Surgical 316L stainless steel bracelet with butterfly clasp", "Luminous Super-LumiNova hour indices for nighttime visibility"]
  },
  {
    id: "watch-3",
    name: "Fitness Band with Blood Oxygen Monitor",
    category: "watches",
    categoryLabel: "Watches & Wearables",
    price: 1999,
    originalPrice: 3999,
    discountPercent: 50,
    rating: 4.5,
    reviewsCount: 7240,
    badge: "Health Track",
    badgeType: "badge-limited",
    inStock: true,
    image: "images/products/fitness_band.jpg",
    description: "All-day fitness tracker with SpO2, stress monitor, menstrual tracking, and 5ATM water resistance. 14-day battery life.",
    features: ["1.1\" AMOLED color display", "SpO2, Heart Rate & Stress monitoring", "100+ workout modes auto-detection", "14-day battery life", "5ATM water resistance — swim-proof"]
  },

  // ══════════════════════════════════════════════════════════════
  //  ELECTRONICS & TECH
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-5",
    name: "Quantum G15 Ultra 5G Smartphone (256GB)",
    category: "electronics",
    categoryLabel: "Electronics & Tech",
    price: 24999,
    originalPrice: 31999,
    discountPercent: 22,
    rating: 4.6,
    reviewsCount: 3410,
    badge: "Hot Pick",
    badgeType: "badge-exclusive",
    inStock: true,
    image: "images/products/quantum_smartphone.jpg",
    description: "Flagship-grade power with Snapdragon processor, 120Hz Super AMOLED curved display, 108MP OIS camera, and 67W Turbo Flash charging with charger in box.",
    features: ["6.7\" Curved 120Hz AMOLED HDR10+ Display", "108MP Triple Camera setup with 4K 60fps recording", "Snapdragon 7+ Gen 2 processor with vapor chamber cooling", "5000 mAh battery with 67W fast charging (0-100% in 38 mins)", "Dual stereo speakers tuned by Dolby Atmos"]
  },
  {
    id: "prod-6",
    name: "Retro Mechanical RGB Keyboard (Hot-swappable)",
    category: "electronics",
    categoryLabel: "Electronics & Tech",
    price: 3899,
    originalPrice: 6499,
    discountPercent: 40,
    rating: 4.9,
    reviewsCount: 754,
    badge: "Must Have",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/retro_keyboard.jpg",
    description: "Compact 75% layout wireless mechanical keyboard featuring custom lubricated linear switches, sound-dampening silicone pads, and per-key customizable RGB lighting.",
    features: ["Tri-mode connectivity: 2.4GHz, Bluetooth 5.1 & Type-C wired", "Hot-swappable PCB compatible with 3-pin & 5-pin switches", "Double-shot PBT dye-sublimated retro keycaps", "Gasket mounted structure for gentle, thocky acoustics", "4000mAh battery providing up to 200 hours usage without RGB"]
  },
  {
    id: "elec-3",
    name: "Gaming Monitor 27\" 165Hz IPS",
    category: "electronics",
    categoryLabel: "Electronics & Tech",
    price: 18999,
    originalPrice: 27999,
    discountPercent: 32,
    rating: 4.8,
    reviewsCount: 1240,
    badge: "Gaming Pro",
    badgeType: "badge-exclusive",
    inStock: true,
    image: "images/products/gaming_monitor.jpg",
    description: "27-inch QHD IPS gaming monitor with 165Hz refresh rate, 1ms response time, AMD FreeSync Premium, and HDR400. Perfect for competitive gaming.",
    features: ["27\" QHD (2560x1440) IPS panel", "165Hz refresh rate, 1ms GTG response", "AMD FreeSync Premium, G-Sync compatible", "HDR400, 95% DCI-P3 color gamut", "VESA mount + adjustable height stand"]
  },
  {
    id: "elec-4",
    name: "Wireless Gaming Mouse 16000 DPI",
    category: "electronics",
    categoryLabel: "Electronics & Tech",
    price: 2999,
    originalPrice: 5499,
    discountPercent: 45,
    rating: 4.7,
    reviewsCount: 3120,
    badge: "FPS Ready",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/gaming_mouse.jpg",
    description: "Ultralight 2.4GHz wireless gaming mouse with 16000 DPI optical sensor, 70-hour battery, 6 programmable buttons and per-key RGB lighting.",
    features: ["16000 DPI adjustable optical sensor", "2.4GHz 1ms wireless response", "70-hour battery with fast USB-C charging", "6 programmable buttons + scroll wheel", "Weight: only 85g ultralight design"]
  },

  // ══════════════════════════════════════════════════════════════
  //  PHONES & MOBILES
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-27",
    name: "NovaStar X1 Pro 5G (128GB, Midnight Black)",
    category: "phones",
    categoryLabel: "Phones & Mobiles",
    price: 12999,
    originalPrice: 17999,
    discountPercent: 28,
    rating: 4.6,
    reviewsCount: 8740,
    badge: "5G Ready",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/novastar_5g.jpg",
    description: "Powerful 5G smartphone with 50MP triple camera, 5000mAh battery, and 90Hz IPS display. Includes 33W fast charger in box — no compromise on value.",
    features: ["6.5\" 90Hz IPS FHD+ display with Corning Gorilla Glass", "50MP + 8MP + 2MP triple rear camera system", "MediaTek Dimensity 700 5G chipset", "5000mAh battery, 33W fast charging", "128GB storage, expandable up to 1TB via microSD"]
  },
  {
    id: "prod-28",
    name: "ZenPhone Ultra 5G (256GB, Cosmic Blue)",
    category: "phones",
    categoryLabel: "Phones & Mobiles",
    price: 18999,
    originalPrice: 27999,
    discountPercent: 32,
    rating: 4.7,
    reviewsCount: 5320,
    badge: "Camera King",
    badgeType: "badge-exclusive",
    inStock: true,
    image: "images/products/zenphone_5g.jpg",
    description: "Flagship 5G experience with 64MP Sony sensor, 120Hz Super AMOLED curved display, and in-display fingerprint sensor. OIS for blur-free night shots.",
    features: ["6.67\" 120Hz Super AMOLED curved display", "64MP Sony IMX766 OIS primary camera", "Snapdragon 778G 5G processor", "4500mAh + 65W SuperDart charging", "In-display optical fingerprint, NFC & dual stereo speakers"]
  },
  {
    id: "prod-29",
    name: "BudgetKing 4G Smartphone (64GB, Blue)",
    category: "phones",
    categoryLabel: "Phones & Mobiles",
    price: 6999,
    originalPrice: 9999,
    discountPercent: 30,
    rating: 4.3,
    reviewsCount: 12400,
    badge: "Best Value",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/budget_smartphone.jpg",
    description: "Reliable everyday 4G smartphone with large 6000mAh battery, 13MP camera, and 2-day battery life. Perfect entry-level pick for students and first-time users.",
    features: ["6.5\" HD+ IPS display", "13MP rear + 5MP front camera", "MediaTek Helio G37 processor", "6000mAh massive battery with 18W charging", "2GB + 64GB storage, expandable to 512GB"]
  },
  {
    id: "prod-30",
    name: "ProMax Gaming Phone 5G (512GB, Neon Orange)",
    category: "phones",
    categoryLabel: "Phones & Mobiles",
    price: 34999,
    originalPrice: 44999,
    discountPercent: 22,
    rating: 4.8,
    reviewsCount: 2890,
    badge: "Gaming Beast",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/promax_gaming_phone.jpg",
    description: "Ultimate mobile gaming powerhouse with Snapdragon 8 Gen 2, 165Hz AMOLED display, dedicated cooling fan, and 6000mAh battery for non-stop action.",
    features: ["6.8\" 165Hz AMOLED display, 1ms touch response", "Snapdragon 8 Gen 2 with vapor chamber cooling", "6000mAh battery with 120W HyperCharge", "Dual stereo speakers with Dolby Atmos", "Shoulder trigger buttons + RGB lighting strip"]
  },

  // ══════════════════════════════════════════════════════════════
  //  FASHION & APPAREL
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-3",
    name: "Pure Linen Slim Fit Casual Shirt",
    category: "fashion",
    categoryLabel: "Fashion & Apparel",
    price: 1299,
    originalPrice: 2499,
    discountPercent: 48,
    rating: 4.5,
    reviewsCount: 630,
    badge: "Deal of the Day",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/linen_shirt.jpg",
    description: "Crafted from 100% breathable organic French flax linen. Ideal for Indian tropical climates, featuring a mandarin collar and tailored modern silhouette.",
    features: ["100% Premium Organic Linen", "Pre-shrunk fabric with soft enzyme wash", "Contemporary Slim Fit", "Breathable, lightweight, moisture-wicking", "Machine washable with cold gentle cycle"]
  },
  {
    id: "prod-7",
    name: "Vintage Genuine Leather Weekender Duffle Bag",
    category: "fashion",
    categoryLabel: "Fashion & Apparel",
    price: 2499,
    originalPrice: 4999,
    discountPercent: 50,
    rating: 4.6,
    reviewsCount: 420,
    badge: "Handcrafted",
    badgeType: "badge-limited",
    inStock: true,
    image: "images/products/leather_duffle.jpg",
    description: "Handcrafted from full-grain vegetable-tanned leather with heavy-duty YKK antique brass zippers. Features dedicated shoe compartment and water-resistant nylon lining.",
    features: ["100% Full-grain Indian leather with rich patina development", "Dedicated ventilated shoe/laundry compartment", "Heavy-duty brass hardware & reinforced base rivets", "Padded adjustable leather shoulder strap", "Meets standard airline cabin luggage dimensions"]
  },

  // ══════════════════════════════════════════════════════════════
  //  FOOTWEAR
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-4",
    name: "Velocity Nitro Cushioned Running Shoes",
    category: "footwear",
    categoryLabel: "Footwear",
    price: 2899,
    originalPrice: 5999,
    discountPercent: 52,
    rating: 4.9,
    reviewsCount: 2150,
    badge: "Top Rated",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/running_shoes.jpg",
    description: "Designed for high-performance athletes and casual joggers alike. High-rebound nitrogen-infused foam midsole offers responsive energy return with every stride.",
    features: ["Engineered breathable mesh upper", "Nitrogen-infused ultra-cushioned midsole", "High-abrasion anti-slip rubber traction sole", "Ergonomic heel collar prevents ankle friction", "Reflective accents for safe night running"]
  },
  {
    id: "shoe-2",
    name: "Men's Formal Oxford Derby Shoes",
    category: "footwear",
    categoryLabel: "Footwear",
    price: 1999,
    originalPrice: 3999,
    discountPercent: 50,
    rating: 4.7,
    reviewsCount: 1870,
    badge: "Office Classic",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/oxford_shoes.jpg",
    description: "Premium genuine leather formal oxford shoes with cushioned insole and anti-slip rubber sole. Classic brogue detailing for a sharp office look.",
    features: ["Genuine leather upper & lining", "Memory foam cushioned insole", "Anti-slip textured rubber outsole", "Classic brogue perforations", "Sizes 6–12 UK"]
  },
  {
    id: "shoe-3",
    name: "Women's Block Heel Sandals",
    category: "footwear",
    categoryLabel: "Footwear",
    price: 1299,
    originalPrice: 2799,
    discountPercent: 54,
    rating: 4.6,
    reviewsCount: 4320,
    badge: "Party Wear",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/womens_sandals.jpg",
    description: "Elegant block heel sandals with cushioned footbed. Perfect for parties, weddings, and festive occasions. Available in 5 metallic shades.",
    features: ["3-inch block heel for stability & comfort", "Soft padded cushioned footbed", "Ankle strap with buckle closure", "Anti-slip rubber sole", "Available in Gold, Silver, Rose Gold, Black, Nude"]
  },
  {
    id: "shoe-4",
    name: "Sports Canvas Sneakers (Unisex)",
    category: "footwear",
    categoryLabel: "Footwear",
    price: 899,
    originalPrice: 1999,
    discountPercent: 55,
    rating: 4.5,
    reviewsCount: 8940,
    badge: "Everyday Fav",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/canvas_sneakers.jpg",
    description: "Classic canvas sneakers for casual everyday wear. Lightweight, breathable, and comfortable for all-day city walks.",
    features: ["100% canvas upper", "Rubber vulcanized sole", "Cushioned OrthoLite insole", "Machine washable", "Sizes 4–12 UK unisex"]
  },

  // ══════════════════════════════════════════════════════════════
  //  HOME & KITCHEN
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-8",
    name: "Barista Espresso & Cappuccino Coffee Machine",
    category: "home",
    categoryLabel: "Home & Kitchen",
    price: 6499,
    originalPrice: 11999,
    discountPercent: 46,
    rating: 4.7,
    reviewsCount: 940,
    badge: "Popular",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/espresso_machine.jpg",
    description: "20-Bar Italian high-pressure pump extracts rich crema and barista-grade espresso. Includes high-performance stainless steel steam wand for silky microfoam milk texturing.",
    features: ["20-Bar professional Italian Ulka pressure pump", "Stainless steel high-pressure steam wand for latte art", "Fast Thermo-block heating ready in 45 seconds", "1.5 Liter detachable transparent water tank", "Dual temperature gauge for precise brew control"]
  },
  {
    id: "prod-11",
    name: "Aroma Diffuser & Ultrasonic Humidifier",
    category: "home",
    categoryLabel: "Home & Kitchen",
    price: 1499,
    originalPrice: 2999,
    discountPercent: 50,
    rating: 4.4,
    reviewsCount: 780,
    badge: "Trending",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/aroma_diffuser.jpg",
    description: "Elevate your living space with silent ultrasonic mist technology, 7 soothing ambient LED mood lights, and automatic shut-off when water runs out.",
    features: ["500ml capacity providing up to 12 hours continuous mist", "Whisper-quiet operation (<22 dB) ideal for restful sleep", "7-color LED mood lighting with warm glow option", "Timer settings (1H, 3H, 6H, Continuous)", "BPA-free medical-grade materials safe for babies and pets"]
  },
  {
    id: "home-3",
    name: "Non-Stick Cookware Set (5 Piece)",
    category: "home",
    categoryLabel: "Home & Kitchen",
    price: 2999,
    originalPrice: 6999,
    discountPercent: 57,
    rating: 4.6,
    reviewsCount: 3420,
    badge: "Kitchen Essential",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/cookware_set.jpg",
    description: "Premium 5-piece non-stick cookware set with PFOA-free granite coating. Suitable for all cooktops including induction. Dishwasher safe.",
    features: ["PFOA-free granite non-stick coating", "Suitable for all cooktops including induction", "Tempered glass lids with steam vent", "5-piece set: 3 pans + 2 pots", "Dishwasher safe, oven safe to 220°C"]
  },
  {
    id: "home-4",
    name: "Air Purifier with HEPA H13 Filter",
    category: "home",
    categoryLabel: "Home & Kitchen",
    price: 7999,
    originalPrice: 14999,
    discountPercent: 47,
    rating: 4.8,
    reviewsCount: 1890,
    badge: "Clean Air",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/air_purifier.jpg",
    description: "True HEPA H13 filter removes 99.97% of particles including PM2.5, pollen, pet dander, and smoke. Covers rooms up to 360 sq ft. Smart auto mode.",
    features: ["HEPA H13 + Activated Carbon 3-layer filter", "Covers up to 360 sq ft in 15 minutes", "Smart air quality sensor with auto mode", "Whisper-quiet 25dB sleep mode", "Compatible with Alexa & Google Home"]
  },
  {
    id: "home-5",
    name: "Instant Electric Kettle 1.5L (Stainless)",
    category: "home",
    categoryLabel: "Home & Kitchen",
    price: 999,
    originalPrice: 2199,
    discountPercent: 55,
    rating: 4.7,
    reviewsCount: 12340,
    badge: "Fast Boil",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/electric_kettle.jpg",
    description: "Stainless steel 1.5L electric kettle with auto shut-off, boil-dry protection and concealed heating element. Boils 1L water in just 4 minutes.",
    features: ["Food-grade 304 stainless steel interior", "1500W rapid boil in 4 minutes", "Auto shut-off & boil-dry protection", "360° cordless rotating base", "Cool-touch handle with indicator light"]
  },

  // ══════════════════════════════════════════════════════════════
  //  MEN'S CLOTHING
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-13",
    name: "Men's Classic Cotton Kurta (Pack of 2)",
    category: "men",
    categoryLabel: "Men's Clothing",
    price: 999,
    originalPrice: 2199,
    discountPercent: 55,
    rating: 4.6,
    reviewsCount: 2340,
    badge: "Combo Deal",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/mens_kurta.jpg",
    description: "Traditional pure cotton kurtas in vibrant ethnic prints. Perfect for festivals, casual outings, and family functions. Available in sizes S–3XL.",
    features: ["100% Premium Sanforized Cotton fabric", "Machine washable, pre-shrunk", "2 kurtas in 1 pack – complementary colors", "Sizes available: S / M / L / XL / 2XL / 3XL", "Ideal for Diwali, Eid & casual wear"]
  },
  {
    id: "prod-14",
    name: "Men's Slim Fit Stretch Chinos (Dark Navy)",
    category: "men",
    categoryLabel: "Men's Clothing",
    price: 1199,
    originalPrice: 2499,
    discountPercent: 52,
    rating: 4.5,
    reviewsCount: 1820,
    badge: "Office Ready",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/mens_chinos.jpg",
    description: "Tailored slim-fit chinos crafted from 4-way stretch cotton blend. Wrinkle-resistant and breathable for all-day comfort from office to evening.",
    features: ["98% Cotton + 2% Lycra stretch blend", "Slim fit, tapered leg silhouette", "Wrinkle-resistant, quick-dry fabric", "Zip fly with button closure, 4 pockets", "Machine washable – no ironing needed"]
  },
  {
    id: "prod-15",
    name: "Men's Graphic Oversized Hoodie",
    category: "men",
    categoryLabel: "Men's Clothing",
    price: 1499,
    originalPrice: 2999,
    discountPercent: 50,
    rating: 4.7,
    reviewsCount: 3120,
    badge: "Street Style",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/mens_hoodie.jpg",
    description: "Premium fleece-lined oversized hoodie with bold graphic print. Soft brushed inner lining keeps you cozy through Indian winters.",
    features: ["320 GSM French Terry fleece fabric", "Oversized relaxed fit with drop shoulders", "Kangaroo pocket and adjustable drawcord", "Ribbed cuffs and hem for shape retention", "Soft brushed fleece lining for extra warmth"]
  },
  {
    id: "prod-16",
    name: "Men's Formal Blazer (Slim Fit, Charcoal)",
    category: "men",
    categoryLabel: "Men's Clothing",
    price: 2799,
    originalPrice: 5999,
    discountPercent: 53,
    rating: 4.8,
    reviewsCount: 940,
    badge: "Premium",
    badgeType: "badge-exclusive",
    inStock: true,
    image: "images/products/formal_blazer.jpg",
    description: "Sophisticated slim-fit formal blazer in premium polyester-viscose blend. Perfect for weddings, interviews, and corporate events.",
    features: ["Poly-viscose premium structured fabric", "Notched lapel with functional button cuffs", "Slim fit with structured shoulder padding", "Inner satin lining with 3 interior pockets", "Dry-clean recommended for best results"]
  },
  {
    id: "prod-17",
    name: "Men's Dri-Fit Sports T-Shirt (Pack of 3)",
    category: "men",
    categoryLabel: "Men's Clothing",
    price: 799,
    originalPrice: 1799,
    discountPercent: 56,
    rating: 4.5,
    reviewsCount: 5420,
    badge: "Value Pack",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/sports_tshirt.jpg",
    description: "Moisture-wicking polyester dry-fit t-shirts ideal for gym, running, cricket, and all outdoor sports. Lightweight and breathable.",
    features: ["100% Polyester Dry-Fit moisture wicking", "Anti-odor silver ion technology", "UPF 30+ sun protection", "Pack of 3 – assorted bright colors", "Tagless neck label for irritation-free wear"]
  },
  {
    id: "men-9",
    name: "Men's Ethnic Nehru Jacket (Festive)",
    category: "men",
    categoryLabel: "Men's Clothing",
    price: 1499,
    originalPrice: 3499,
    discountPercent: 57,
    rating: 4.7,
    reviewsCount: 820,
    badge: "Festive Special",
    badgeType: "badge-limited",
    inStock: true,
    image: "images/products/nehru_jacket.jpg",
    description: "Elegant Nehru jacket in premium jacquard fabric. Perfect for Diwali, weddings, and festive occasions.",
    features: ["Jacquard fabric with ethnic texture", "Mandarin collar (Nehru style)", "Full-front zip closure", "Slim fit silhouette", "Dry clean recommended"]
  },
  {
    id: "men-10",
    name: "Men's Ripped Slim Fit Jeans (Dark Blue)",
    category: "men",
    categoryLabel: "Men's Clothing",
    price: 1099,
    originalPrice: 2499,
    discountPercent: 56,
    rating: 4.5,
    reviewsCount: 5720,
    badge: "Street Style",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/ripped_jeans.jpg",
    description: "Trendy ripped slim-fit jeans with stretch denim for ultimate comfort and style.",
    features: ["Stretch denim: 98% Cotton + 2% Elastane", "Slim fit tapered leg", "Fashion rip & distress details", "5-pocket construction", "Machine washable"]
  },
  {
    id: "men-17",
    name: "Men's Cotton Dhoti Kurta Set",
    category: "men",
    categoryLabel: "Men's Clothing",
    price: 1299,
    originalPrice: 2799,
    discountPercent: 54,
    rating: 4.8,
    reviewsCount: 1560,
    badge: "Ethnic Set",
    badgeType: "badge-limited",
    inStock: true,
    image: "images/products/dhoti_kurta.jpg",
    description: "Traditional pure cotton dhoti kurta set for pujas, weddings, and festive occasions.",
    features: ["100% Pure cotton fabric", "Traditional dhoti + matching kurta", "Comfortable for all-day wear", "Machine washable", "Available in White, Cream, Off-White"]
  },

  // ══════════════════════════════════════════════════════════════
  //  WOMEN'S CLOTHING
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-18",
    name: "Women's Floral Anarkali Kurti (Rayon)",
    category: "women",
    categoryLabel: "Women's Clothing",
    price: 849,
    originalPrice: 1999,
    discountPercent: 58,
    rating: 4.7,
    reviewsCount: 4320,
    badge: "Ethnic Wear",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/anarkali_kurti.jpg",
    description: "Graceful floral printed Anarkali kurti in soft rayon fabric. Perfect for casual outings, office wear, and festive occasions.",
    features: ["Soft premium rayon fabric", "Allover floral block print", "A-line Anarkali silhouette with side slits", "Round neck with button placket", "Sizes: XS / S / M / L / XL / XXL / 3XL"]
  },
  {
    id: "prod-19",
    name: "Women's Saree with Unstitched Blouse Piece",
    category: "women",
    categoryLabel: "Women's Clothing",
    price: 1599,
    originalPrice: 3499,
    discountPercent: 54,
    rating: 4.9,
    reviewsCount: 2870,
    badge: "Wedding Season",
    badgeType: "badge-exclusive",
    inStock: true,
    image: "images/products/saree_blouse.jpg",
    description: "Exquisite embroidered georgette saree with zari border and complementary unstitched blouse piece. Elegant drape for weddings and special occasions.",
    features: ["Premium georgette fabric, 5.5 metres", "Zari & thread embroidery border", "Comes with matching unstitched blouse piece", "Dry wash or gentle hand wash only", "Available in 8 rich festive colors"]
  },
  {
    id: "prod-20",
    name: "Women's High-Waist Yoga Leggings",
    category: "women",
    categoryLabel: "Women's Clothing",
    price: 699,
    originalPrice: 1499,
    discountPercent: 53,
    rating: 4.6,
    reviewsCount: 6810,
    badge: "Activewear",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/yoga_leggings.jpg",
    description: "Buttery-soft 4-way stretch high-waist leggings designed for yoga, pilates, and gym. Squat-proof with hidden waistband pocket.",
    features: ["80% Nylon + 20% Spandex 4-way stretch", "High-rise 25cm waistband, no roll-down", "Squat-proof, opaque fabric", "Hidden inner waistband pocket", "Moisture-wicking, quick-dry technology"]
  },
  {
    id: "prod-21",
    name: "Women's Crop Sweatshirt & Jogger Co-ord Set",
    category: "women",
    categoryLabel: "Women's Clothing",
    price: 1299,
    originalPrice: 2799,
    discountPercent: 54,
    rating: 4.7,
    reviewsCount: 3450,
    badge: "Co-ord Set",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/crop_sweatshirt_set.jpg",
    description: "Cozy crop sweatshirt paired with matching relaxed joggers. Perfect loungewear for working from home or casual weekend outings.",
    features: ["280 GSM French Terry cotton blend", "Crop top + jogger 2-piece set", "Elasticated waistband with drawstring", "Ribbed cuffs and hem", "Available in 6 pastel and earth-tone colors"]
  },
  {
    id: "women-7",
    name: "Women's Rayon Maxi Dress (Floral)",
    category: "women",
    categoryLabel: "Women's Clothing",
    price: 999,
    originalPrice: 2199,
    discountPercent: 55,
    rating: 4.6,
    reviewsCount: 5430,
    badge: "Summer Favourite",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/rayon_maxi_dress.jpg",
    description: "Breezy floral maxi dress in soft rayon. Ideal for beach trips, casual outings, and summer parties.",
    features: ["Soft rayon fabric", "Allover floral print", "Spaghetti straps, maxi length", "Back elastic for comfortable fit", "Sizes XS to 3XL"]
  },


  // ══════════════════════════════════════════════════════════════
  //  KIDS' CLOTHING
  // ══════════════════════════════════════════════════════════════
  {
    id: "prod-23",
    name: "Kids' Cartoon Printed T-Shirt (Pack of 5)",
    category: "kids",
    categoryLabel: "Kids' Clothing",
    price: 799,
    originalPrice: 1999,
    discountPercent: 60,
    rating: 4.8,
    reviewsCount: 7820,
    badge: "Kids Fav",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/kids_tshirts.jpg",
    description: "Super soft cotton t-shirts with vibrant cartoon character prints. Pre-shrunk, comfortable, and durable for active kids aged 2–12 years.",
    features: ["100% soft combed cotton, 180 GSM", "Pre-shrunk, stays soft after washing", "Pack of 5 different cartoon prints", "Non-toxic, skin-safe reactive dyes", "Sizes: 2–3Y / 3–4Y / 4–5Y / 6–7Y / 8–9Y / 10–11Y / 12–13Y"]
  },

  {
    id: "kids-5",
    name: "Kids' School Backpack (Waterproof)",
    category: "kids",
    categoryLabel: "Kids' Clothing",
    price: 699,
    originalPrice: 1499,
    discountPercent: 53,
    rating: 4.7,
    reviewsCount: 6340,
    badge: "School Must",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/kids_backpack.jpg",
    description: "Ergonomic waterproof school bag with padded shoulder straps, reflective strip, and multiple compartments for books, bottles, and stationery.",
    features: ["Waterproof 600D polyester fabric", "Padded back panel & shoulder straps", "Main compartment + 3 pockets + bottle holder", "Reflective safety strip", "Capacity: 20L — ideal for classes 1–8"]
  },

  // ══════════════════════════════════════════════════════════════
  //  ACCESSORIES
  // ══════════════════════════════════════════════════════════════

  {
    id: "prod-32",
    name: "Polarized UV400 Aviator Sunglasses",
    category: "accessories",
    categoryLabel: "Accessories",
    price: 699,
    originalPrice: 1599,
    discountPercent: 56,
    rating: 4.5,
    reviewsCount: 6730,
    badge: "UV Protection",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/aviator_sunglasses.jpg",
    description: "Classic metal-frame aviator sunglasses with polarized lenses offering 100% UV400 protection. Lightweight spring hinge temples.",
    features: ["Polarized TAC lenses with UV400 protection", "Lightweight stainless steel frame", "Spring hinge for flexible, comfortable fit", "Anti-scratch, anti-glare coated lenses", "Includes hard case + microfiber cleaning cloth"]
  },
  {
    id: "prod-33",
    name: "RFID Blocking Slim Leather Wallet (Men's)",
    category: "accessories",
    categoryLabel: "Accessories",
    price: 499,
    originalPrice: 1199,
    discountPercent: 58,
    rating: 4.7,
    reviewsCount: 9120,
    badge: "Anti-Theft",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/rfid_wallet.jpg",
    description: "Ultra-slim bi-fold genuine leather wallet with RFID blocking shield. Fits up to 8 cards plus cash.",
    features: ["Genuine top-grain leather construction", "RFID blocking technology in all card slots", "Holds 6–8 cards + cash compartment", "Slim profile: only 8mm thin when loaded", "Available in Black, Brown, Dark Tan"]
  },
  {
    id: "prod-34",
    name: "Women's Pearl & Crystal Jewellery Set",
    category: "accessories",
    categoryLabel: "Accessories",
    price: 799,
    originalPrice: 1999,
    discountPercent: 60,
    rating: 4.8,
    reviewsCount: 5640,
    badge: "Gift Worthy",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/pearl_jewellery_set.jpg",
    description: "Elegant 4-piece pearl and crystal jewellery set: necklace, earrings, bracelet, and ring. Hypoallergenic, tarnish-resistant alloy.",
    features: ["4-piece set: necklace + earrings + bracelet + ring", "Hypoallergenic, nickel-free alloy base", "Freshwater pearl finish with crystal accents", "Gold-plated chain and clasps", "Comes in premium gift-ready box"]
  },
  {
    id: "prod-35",
    name: "20000mAh Power Bank (PD 22.5W Fast Charge)",
    category: "accessories",
    categoryLabel: "Accessories",
    price: 1299,
    originalPrice: 2999,
    discountPercent: 57,
    rating: 4.7,
    reviewsCount: 14280,
    badge: "20000 mAh",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/power_bank.jpg",
    description: "Compact 20000mAh power bank with dual USB-A + USB-C PD output. Charges most smartphones 4–5 times. BIS certified for safety.",
    features: ["20000mAh real capacity, BIS certified", "USB-C PD 22.5W output for fast charging", "Dual USB-A 18W QC 3.0 output", "LED indicator shows remaining charge", "Can charge 2 devices simultaneously"]
  },
  {
    id: "prod-36",
    name: "Stainless Steel Insulated Water Bottle (1L)",
    category: "accessories",
    categoryLabel: "Accessories",
    price: 549,
    originalPrice: 1299,
    discountPercent: 58,
    rating: 4.9,
    reviewsCount: 22450,
    badge: "Eco Choice",
    badgeType: "badge-limited",
    inStock: true,
    image: "images/products/water_bottle.jpg",
    description: "Double-wall vacuum insulated 1L stainless steel bottle keeps drinks cold 24hrs and hot 12hrs. Leak-proof and BPA-free.",
    features: ["18/8 food-grade stainless steel", "Double-wall vacuum insulation technology", "Keeps cold 24 hours / hot 12 hours", "Leak-proof screw cap + carrying loop", "BPA-free, sweat-free exterior"]
  },


  // ══════════════════════════════════════════════════════════════
  //  FRAGRANCE
  // ══════════════════════════════════════════════════════════════
  {
    id: "frag-1",
    name: "Royal Oud Luxury Attar (12ml)",
    category: "fragrance",
    categoryLabel: "Fragrance",
    price: 1499,
    originalPrice: 2999,
    discountPercent: 50,
    rating: 4.9,
    reviewsCount: 3240,
    badge: "Bestseller",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/royal_oud_attar.jpg",
    description: "Pure non-alcoholic oud attar crafted from aged Assamese agarwood. Rich, woody, and long-lasting — a signature scent for special occasions.",
    features: ["100% pure non-alcoholic attar", "Aged Assamese agarwood oud base", "Lasts 8–10 hours on skin", "Comes in decorative glass bottle with dropper", "Suitable for men & women"]
  },
  {
    id: "frag-2",
    name: "Fresh Aqua Men's Eau de Parfum (100ml)",
    category: "fragrance",
    categoryLabel: "Fragrance",
    price: 899,
    originalPrice: 1999,
    discountPercent: 55,
    rating: 4.6,
    reviewsCount: 6780,
    badge: "Popular",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/fresh_aqua_perfume.jpg",
    description: "Crisp, ocean-inspired Eau de Parfum. Top notes of citrus and sea breeze, heart of driftwood and musk, base of white cedar and vetiver.",
    features: ["100ml Eau de Parfum, long-lasting formula", "Top: Bergamot, aquatic accords, lime", "Heart: Driftwood, jasmine, spices", "Base: Cedarwood, vetiver, white musk", "Handcrafted in India"]
  },
  {
    id: "frag-3",
    name: "Rose Oud Luxury Perfume Gift Set",
    category: "fragrance",
    categoryLabel: "Fragrance",
    price: 1999,
    originalPrice: 3999,
    discountPercent: 50,
    rating: 4.8,
    reviewsCount: 2130,
    badge: "Gift Set",
    badgeType: "badge-limited",
    inStock: true,
    image: "images/products/rose_oud_perfume.jpg",
    description: "Premium gift set with 50ml rose oud EDP, travel spray, and scented body lotion. Perfect for gifting on birthdays, anniversaries, and festivals.",
    features: ["3-piece set: 50ml EDP + 10ml travel spray + 100ml body lotion", "Blend of Turkish rose and Cambodian oud", "Gift-ready premium packaging", "Alcohol-based, EU compliant formula", "Unisex fragrance"]
  },



  // ══════════════════════════════════════════════════════════════
  //  BAGS & LEATHER GOODS
  // ══════════════════════════════════════════════════════════════
  {
    id: "bag-1",
    name: "Women's Trendy Tote Bag (Canvas)",
    category: "bags",
    categoryLabel: "Bags & Leather",
    price: 799,
    originalPrice: 1799,
    discountPercent: 56,
    rating: 4.6,
    reviewsCount: 7430,
    badge: "Everyday Carry",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/tote_bag.jpg",
    description: "Spacious canvas tote bag with zip closure, inner pockets, and sturdy shoulder straps. Fits 14-inch laptop. Perfect for college, office, and travel.",
    features: ["Heavy-duty 12oz canvas exterior", "Zip top closure + inner zip pocket", "Fits 14\" laptop in padded sleeve", "Reinforced stitched handles", "Available in 10 prints and colors"]
  },
  {
    id: "bag-2",
    name: "Leather Laptop Backpack (15.6 inch)",
    category: "bags",
    categoryLabel: "Bags & Leather",
    price: 1899,
    originalPrice: 3999,
    discountPercent: 53,
    rating: 4.7,
    reviewsCount: 4320,
    badge: "Office Pro",
    badgeType: "badge-new",
    inStock: true,
    image: "images/products/laptop_backpack.jpg",
    description: "Premium PU leather laptop backpack with USB charging port, anti-theft back pocket, and ergonomic padded straps. 30L capacity.",
    features: ["Fits 15.6\" laptop in padded compartment", "Built-in USB charging port & earphone hole", "Anti-theft hidden pocket on back", "Ergonomic padded air-mesh shoulder straps", "30L capacity — carry-on airline compliant"]
  },
  {
    id: "bag-3",
    name: "Ethnic Embroidered Sling Bag",
    category: "bags",
    categoryLabel: "Bags & Leather",
    price: 699,
    originalPrice: 1499,
    discountPercent: 53,
    rating: 4.5,
    reviewsCount: 3120,
    badge: "Boho Chic",
    badgeType: "badge-sale",
    inStock: true,
    image: "images/products/ethnic_sling_bag.jpg",
    description: "Handcrafted Rajasthani embroidered sling bag with mirror work. Perfect for festivals, markets, and casual outings.",
    features: ["Hand embroidered with mirror work", "Rajasthani ethnic design", "Adjustable strap — shoulder or crossbody", "Zip closure with inner pocket", "Approximately 25 x 20 cm size"]
  }

];
